[package]
name = "wgltf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { version = "1.13.1", features = ["derive", "nightly_stdsimd"] }
color-eyre = "0.6.2"
dolly = "0.4.1"
either = "1.8.1"
env_logger = "0.10.0"
glam = { version = "0.23.0", features = ["core-simd", "rand", "bytemuck"] }
gltf = "1.1.0"
image = { version = "0.24.5", default-features = false, features = [
	"jpeg",
	"png",
] }
log = "0.4.17"
pollster = { version = "0.3.0", features = ["macro"] }
tobj = "3.2.4"
wgpu = { version = "0.15.1", features = ["spirv", "naga"] }
wgpu-profiler = "0.11.0"
winit = "0.28.3"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.3"
glob = "0.3"

[profile.dev.package."*"]
opt-level = 1

[profile.profiling]
inherits = "release"
debug = true
