[package]
name = "wgltf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
color-eyre = "0.6.2"
either = "1.8.1"
bytemuck = { version = "1.13.1", features = ["derive", "nightly_stdsimd"] }
dolly = "0.4.1"
glam = { version = "0.23.0", features = ["core-simd", "rand", "bytemuck"] }
gltf = "1.1.0"
tobj = "3.2.4"
image = { version = "0.24.5", default-features = false, features = [
	"jpeg",
	"png",
] }
notify = "5.1.0"
notify-debouncer-mini = "0.2.1"
slotmap = "1.0.6"
indexmap = "1.9.3"
pollster = { version = "0.3.0", features = ["macro"] }
wgpu = { version = "0.15.1", features = ["spirv", "naga"] }
wgpu-profiler = "0.11.0"
winit = "0.28.3"
naga = { version = "0.11.0", features = [
	"spv-out",
	"wgsl-in",
	"validate",
	"span",
] }
once_cell = "1.17.1"
parking_lot = "0.12.1"

[profile.dev.package."*"]
opt-level = 1

[profile.profiling]
inherits = "release"
debug = true
